# Basic Information 
title: Robert Jankowski
position: Postdoctoral Fellow
affiliation: TU Delft
affiliation_link: https://www.nas.ewi.tudelft.nl/
affiliation_logo: ./assets/img/logo_tudelft.svg
email: research (at) robertjankowski.net

# Search Engine Optimization (SEO)
keywords: robert jankowski, jankowski
canonical: https://robertjankowski.github.io
description: Robert Jankowski is a Postdoctoral Fellow at TU Delft. His research lies in network geometry, network embedding and machine learning.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=lmMHrzcAAAAJ&hl=en
cv_link: /assets/jankowski_CV.pdf
github_link: https://github.com/robertjankowski
linkedin: https://www.linkedin.com/in/robert--jankowski/
google_analytics: G-RWMF4BL9PD

# Images 
avatar: https://robertjankowski.github.io/assets/img/rj_photo.jpg

# Footnotes
footnote: Based on this amazing template
footnote_link: https://github.com/yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
